version: '3'

services:
  notification-postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: schedule
    ports:
      - "5432:5432"
