name: Run tests and build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: go test -v ./...

    #- name: Configure AWS credentials
    #  uses: aws-actions/configure-aws-credentials@v1
    #  with:
    #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ECR }}
    #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_ECR }}
    #    aws-region: us-east-1

    #- name: Login to Amazon ECR
    #  id: login-ecr
    #  uses: aws-actions/amazon-ecr-login@v1

    #- name: Build, tag, and push the image to Amazon ECR
    #  id: build-image
    #  env:
    #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #    ECR_REPOSITORY: hybris-backend
    #    IMAGE_TAG: latest
    #  run: |
    #    # Build a docker container and push it to ECR 
    #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
    #    echo "Pushing image to ECR..."
    #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    #    echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
